// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOZJQO46FMDDEUuqdvkOFuZsNGeaF1kE',
    appId: '1:682441097900:android:6f9815fd07cfcc9fbe1509',
    messagingSenderId: '682441097900',
    projectId: 'shop-app-c3017',
    databaseURL: 'https://shop-app-c3017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-c3017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfTayWo8Ge7HVJy2_CVdLir7FkWKQGPU',
    appId: '1:682441097900:ios:dbda02d884971787be1509',
    messagingSenderId: '682441097900',
    projectId: 'shop-app-c3017',
    databaseURL: 'https://shop-app-c3017-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-c3017.appspot.com',
    androidClientId: '682441097900-o0bkt8qba1eab16jbsqpcg0od7q4gh2i.apps.googleusercontent.com',
    iosClientId: '682441097900-dod90pj7o994re6hf59grohvdqlfnqos.apps.googleusercontent.com',
    iosBundleId: 'com.beeshop.shopAppClient',
  );
}
