// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSYuVb9OwMtJlY7Kp7HaivKP3nrckqMs',
    appId: '1:1011459206295:android:5e796083218d8a57fe0dd2',
    messagingSenderId: '1011459206295',
    projectId: 'hj-express-9a264',
    databaseURL: 'https://hj-express-9a264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hj-express-9a264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNWmh5Mrohqdts44-fDhIwOrM-p3LeTWQ',
    appId: '1:1011459206295:ios:822f67b4511236e9fe0dd2',
    messagingSenderId: '1011459206295',
    projectId: 'hj-express-9a264',
    databaseURL: 'https://hj-express-9a264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hj-express-9a264.appspot.com',
    androidClientId: '1011459206295-2hd9qeht0krg4mj6j2qifnoh03i1nh7l.apps.googleusercontent.com',
    iosClientId: '1011459206295-is63n7k9rvir9ufokkmq47jfj91nfalh.apps.googleusercontent.com',
    iosBundleId: 'com.huijing.jiyunAppClient',
  );
}
